// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unix.Data;

#nullable disable

namespace Unix.Data.Migrations
{
    [DbContext(typeof(UnixContext))]
    [Migration("20211231041928_AutoRole_Init")]
    partial class AutoRole_Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unix.Data.Models.Core.GuildConfiguration", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("AdministratorRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal[]>("AutoRoles")
                        .HasColumnType("numeric(20,0)[]");

                    b.Property<bool>("AutomodEnabled")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("BannedTerms")
                        .HasColumnType("text[]");

                    b.Property<ulong>("MessageLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("MiscellaneousLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("ModLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("ModeratorRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PhishermanApiKey")
                        .HasColumnType("text");

                    b.Property<ulong>("RequiredRoleToUse")
                        .HasColumnType("numeric(20,0)");

                    b.Property<List<decimal>>("SelfAssignableRoles")
                        .HasColumnType("numeric[]");

                    b.Property<List<decimal>>("WhitelistedInvites")
                        .HasColumnType("numeric[]");

                    b.HasKey("Id");

                    b.ToTable("GuildConfigurations");
                });

            modelBuilder.Entity("Unix.Data.Models.Core.Reminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Unix.Data.Models.Core.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .HasColumnType("citext");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Unix.Data.Models.Moderation.Infraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsRescinded")
                        .HasColumnType("boolean");

                    b.Property<ulong>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<ulong>("SubjectId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Infractions");
                });
#pragma warning restore 612, 618
        }
    }
}
