// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unix.Data;

namespace Unix.Data.Migrations
{
    [DbContext(typeof(UnixContext))]
    [Migration("20211012013340_ReduceHardships")]
    partial class ReduceHardships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Unix.Data.Models.Core.BlacklistedGuild", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedGuilds");
                });

            modelBuilder.Entity("Unix.Data.Models.Core.BlacklistedUser", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedUsers");
                });

            modelBuilder.Entity("Unix.Data.Models.Core.GuildConfiguration", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("AdministratorRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("AutomodEnabled")
                        .HasColumnType("boolean");

                    b.Property<ulong>("MessageLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("ModLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("ModeratorRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("MuteRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<ulong>("UserJoinedLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("GuildConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
