// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unix.Data;

namespace Unix.Data.Migrations
{
    [DbContext(typeof(UnixContext))]
    [Migration("20211126024040_RemovePrefix")]
    partial class RemovePrefix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Unix.Data.Models.Core.GuildConfiguration", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("AdministratorRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("AmountOfMessagesConsideredSpam")
                        .HasColumnType("integer");

                    b.Property<bool>("AutomodEnabled")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("BannedTerms")
                        .HasColumnType("text[]");

                    b.Property<ulong>("MessageLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("ModLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("ModeratorRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("MuteRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("RequiredRoleToUse")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal[]>("SelfAssignableRoles")
                        .HasColumnType("numeric(20,0)[]");

                    b.Property<decimal[]>("WhitelistedInvites")
                        .HasColumnType("numeric(20,0)[]");

                    b.HasKey("Id");

                    b.ToTable("GuildConfigurations");
                });

            modelBuilder.Entity("Unix.Data.Models.Moderation.Infraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<ulong>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<ulong>("SubjectId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Infractions");
                });
#pragma warning restore 612, 618
        }
    }
}
